### ISSUE TITLE
Abort fetches on "navigation" to a different user

### ISSUE THREAD

**Issue by domfarolino** [domfarolino/pages#3]
Right now we don't abort fetches upon single-page "navigation" which means a previous user's GitHub projects may be listed under another user if the navigation is performed "too quick". We should abort all outstanding fetches just before we actually perform a navigation.

**Comment by musgravejw** [comment]
Does this only happen on the repository list, or is it also the user list?

Is a vanilla JS event handler ok here?

**Comment by domfarolino** [comment]
I think it happens everywhere but not sure. I'm not following the question about vanilla JS event handlers, where are you thinking they'd go? I think we need a list of AbortControllers for all fetches, and then whenever we call one of the `update()` UI functions we can just abort all the fetches etc. We can do this right before we call `replaceChildren()` on the list outputs.

**Comment by musgravejw** [comment]
Not sure, I was thinking of how to call the abort controller.  But, that would only be for one fetch.

**Comment by domfarolino** [comment]
Closed in https://github.com/domfarolino/pages/pull/4.
